[detectors]
exclude = [
    "reentrancy",
    "balance-relied-on",
    "unprotected-selfdestruct",
    "unsafe-erc20-call",
    "unchecked-return-value",
    "divide-before-multiply",
    "missing-return",
    "unused-function",
    "locked-ether",
]
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["node_modules", "lib", "script"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"