[compiler.solc]
exclude_paths = ["node_modules", "venv", ".venv", "lib", "script", "test"]
include_paths = ["node_modules"]
evm_version = "istanbul"

[detectors]
exclude = [
    "reentrancy",
    "balance-relied-on",
    "unprotected-selfdestruct",
    "unsafe-erc20-call",
    "unchecked-return-value",
    "divide-before-multiply",
    "missing-return",
    "unused-function",
    "locked-ether",
]
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["node_modules", "lib", "script"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent --hardfork paris"

[testing.ganache]
cmd_args = "-k paris -q"

[testing.hardhat]
cmd_args = ""
